import { _electron as electron, expect, test } from '@playwright/test'
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

test('plain click opens the image modal, navigation resets zoom, Escape restores focus and wheel stays isolated', async () => {
  const root = await mkdtemp(join(tmpdir(), 'inknest-image-viewer-'))
  const document = join(root, 'images.md')
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aOccAAAAASUVORK5CYII=', 'base64')
  await writeFile(join(root, 'one.png'), png)
  await writeFile(join(root, 'two.png'), png)
  await writeFile(document, '# Images\n\n![第一张](one.png)\n\n![第二张](two.png)\n\n' + 'Long text\n\n'.repeat(100))
  const app = await electron.launch({ ...(process.env.INKNEST_PACKAGED_EXECUTABLE ? { executablePath: process.env.INKNEST_PACKAGED_EXECUTABLE } : {}), args: [...(process.env.INKNEST_PACKAGED_EXECUTABLE ? [] : ['.']), `--user-data-dir=${join(root, 'profile')}`], chromiumSandbox: true })
  try {
    const page = await app.firstWindow({ timeout: 10000 })
    await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }) }, document)
    await page.getByRole('button', { name: '打开文档', exact: true }).first().click()
    const origin = page.locator('.preview img').first()
    await expect.poll(() => origin.evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(1)
    await origin.click()
    const viewer = page.getByRole('dialog', { name: '图片查看器' })
    await expect(viewer).toBeVisible()
    await expect(viewer.locator('img')).toHaveAttribute('draggable', 'false')
    await viewer.getByRole('button', { name: '放大图片', exact: true }).click()
    await expect(viewer.locator('.image-viewer-scale')).toHaveText('125%')
    await viewer.getByRole('button', { name: '下一张图片', exact: true }).click()
    await expect(viewer.getByAltText('第二张')).toBeVisible()
    await expect(viewer.locator('.image-viewer-scale')).toHaveText('100%')
    await viewer.locator('.image-viewer-viewport').focus()
    await page.keyboard.press('ArrowLeft')
    await expect(viewer.getByAltText('第一张')).toBeVisible()
    await page.keyboard.press('ArrowRight')
    await expect(viewer.getByAltText('第二张')).toBeVisible()
    await viewer.getByRole('button', { name: '放大图片', exact: true }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(viewer.getByAltText('第二张')).toBeVisible()
    const before = await page.locator('.document-stage').evaluate(element => element.scrollTop)
    await viewer.locator('.image-viewer-viewport').hover()
    await page.mouse.wheel(0, 600)
    await page.waitForTimeout(100)
    expect(await page.locator('.document-stage').evaluate(element => element.scrollTop)).toBe(before)
    await page.keyboard.press('Escape')
    await expect(viewer).toHaveCount(0)
    await expect(origin).toBeFocused()
    expect(await page.locator('.document-stage').evaluate(element => element.scrollTop)).toBe(before)
    await origin.click()
    await expect(viewer).toBeVisible()
    await viewer.click({ position: { x: 8, y: 100 } })
    await expect(viewer).toHaveCount(0)
  } finally { const exited = new Promise<void>(resolve => app.process().once('exit', () => resolve())); app.process().kill('SIGKILL'); await exited; await rm(root, { recursive: true, force: true }) }
})

test('single large image fits, zooms with native scrolling, stays still on drag, and resets fit after resizing', async () => {
  const root = await mkdtemp(join(tmpdir(), 'inknest-image-viewer-large-'))
  const document = join(root, 'large.md')
  await writeFile(join(root, 'large.png'), await readFile(join(process.cwd(), 'tests/fixtures/images/viewer-large.png')))
  await writeFile(document, '# Large image\n\n![大图](large.png)')
  const app = await electron.launch({ ...(process.env.INKNEST_PACKAGED_EXECUTABLE ? { executablePath: process.env.INKNEST_PACKAGED_EXECUTABLE } : {}), args: [...(process.env.INKNEST_PACKAGED_EXECUTABLE ? [] : ['.']), `--user-data-dir=${join(root, 'profile')}`], chromiumSandbox: true })
  try {
    const page = await app.firstWindow({ timeout: 10000 })
    await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }) }, document)
    await page.getByRole('button', { name: '打开文档', exact: true }).first().click()
    await test.step('open decoded large fixture in viewer', async () => {
      const previewImage = page.locator('.preview img')
      await expect.poll(() => previewImage.evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(1600)
      await previewImage.click()
    })
    const viewer = page.getByRole('dialog', { name: '图片查看器' })
    await expect(viewer).toBeVisible()
    await expect(viewer.getByRole('button', { name: '下一张图片', exact: true })).toHaveCount(0)
    await expect(viewer.locator('img')).not.toHaveClass(/image-viewer-image-loading/u)
    await viewer.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))) })
    await writeFile(test.info().outputPath('image-viewer.png'), Buffer.from(await app.evaluate(async ({ BrowserWindow }) => [...(await BrowserWindow.getAllWindows()[0]!.webContents.capturePage()).toPNG()])))
    await viewer.getByAltText('大图').dblclick()
    await expect(viewer.locator('.image-viewer-scale')).toHaveText('100%')
    await expect(viewer.getByRole('button', { name: '原始大小', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await viewer.getByAltText('大图').dblclick()
    await expect(viewer.getByRole('button', { name: '适应窗口', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await viewer.getByRole('button', { name: '原始大小', exact: true }).click()
    const viewport = viewer.locator('.image-viewer-viewport')
    await expect.poll(() => viewport.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
    await viewport.hover()
    await page.mouse.wheel(0, 250)
    await expect.poll(() => viewport.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    const beforeDrag = await viewport.evaluate(element => ({ x: element.scrollLeft, y: element.scrollTop }))
    const box = await viewport.boundingBox()
    if (!box) throw new Error('Missing viewport')
    await page.mouse.move(box.x + 250, box.y + 200)
    await page.mouse.down()
    await page.mouse.move(box.x + 350, box.y + 270, { steps: 5 })
    await page.mouse.up()
    await expect(viewer).toBeVisible()
    expect(await viewport.evaluate(element => ({ x: element.scrollLeft, y: element.scrollTop }))).toEqual(beforeDrag)
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setSize(800, 700))
    await viewer.getByRole('button', { name: '适应窗口', exact: true }).click()
    await expect.poll(() => viewport.evaluate(element => element.scrollTop)).toBe(0)
    await expect.poll(() => viewport.evaluate(element => element.scrollHeight <= element.clientHeight)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(viewer).toHaveCount(0)
  } finally { const exited = new Promise<void>(resolve => app.process().once('exit', () => resolve())); app.process().kill('SIGKILL'); await exited; await rm(root, { recursive: true, force: true }) }
})
