import type { ErrorCode, ReadOnlyReason, ResourceBlockedReason } from './contracts'

/** Product language shared by native dialogs and the document workspace. */
export const copy = {
  home: '返回首页', save: '保存',
  saveCurrent: (name: string) => `保存当前文档：${name}`,
  documentActions: (name: string) => `当前文档操作：${name}`, moreDocumentActions: '当前文档的更多操作',
  newDocument: '新建文档', newFailed: '新建失败，已有文档已保留。',
  initialSave: '保存…', initialSaveTitle: '保存 Markdown 文档', initialSaveRequired: '请先保存文档并选择文件位置。',
  unsavedFile: '尚未保存到文件', untitledHistory: '保存为文件后开始记录历史版本。',
  untitledCloseQuestion: (name: string) => `要将“${name}”保存为文件吗？`,
  untitledCloseDetail: '保存后关闭此文档；取消将继续编辑。', dontSave: '不保存…',
  untitledExit: '请先保存或关闭此文档，再退出。',
  saveResultPending: '保存结果尚未确认，内容已保留并暂停编辑。请重试核对原请求。',
  chooseSystemDocument: '请选择要打开的文档',
  chooseSystemDocumentDetail: '一次打开一份文档；其他已打开的文档会保留。',
  historyCleanupFailed: '历史版本已保留，但部分旧备份暂时无法清理，将在后续操作重试。',
  historySavedFailed: '文档已保存，但历史版本未更新。请重试保存；自动保存已暂停。',
  historySkipped: '文档已保存，本次未保留历史。请重试保存；自动保存已暂停。',
  historyCloseQuestion: '文档已保存，但历史版本尚未记录。仍然关闭？',
  historyCloseAnyway: '仍然关闭（正文已保存）',
  historyMerged: '此自动版本已合并或清理，请重新选择历史版本。',
  historySources: { baseline: '修改前版本', auto: '自动保存', manual: '手动保存', close: '关闭保存', 'save-as': '另存为', restore: '还原', legacy: '旧版历史' },
  historyMergeable: '近期自动保存会合并',

  restoreHistoryUnchanged: '当前内容与此版本相同',
  presentation: '进入演示',
  exitPresentation: '退出演示',
  presentationFailed: '未能进入全屏演示，文档内容已保留。',
  presentationChanged: '当前文档状态已变化，退出演示后可处理。',
  viewMenu: '视图',
  historyClose: '关闭历史', historyCurrent: '当前文档', historyReturn: '返回当前文档', historyRestoreEntry: '还原', historyLoading: '正在读取历史…',
  historyToday: '今天', historyYesterday: '昨天', historyEarlier: '更早', historyRestoreBlocked: '请先处理当前文档的只读、冲突或恢复状态。',
  historyNotRestorable: '此版本仅供查看和另存。', historyResultCheck: '核对还原结果', historyResultChecking: '正在核对…',
  historyPending: '有一项还原结果待核对，源文档暂时不可编辑。', backupClose: '关闭本地备份', dismiss: '关闭提示', view: '查看',
  recoveryFound: (count: number) => `发现${count}份未保存稿`, historyPreviewing: (time: string) => `正在预览 ${time} 的历史版本`,
  restoreHistory: '还原此版本',
  restoreHistoryQuestion: (savedAt: string) => `将文档还原到 ${new Date(savedAt).toLocaleTimeString()} 的版本？`,
  restoreHistoryDetail: '当前修改会先保存，并保留还原前的版本。此操作可撤销。',
  restoreHistoryPreserved: '当前修改已保存，还原未完成。',
  restoreHistoryUncertain: '还原结果未确认，已暂停自动保存。当前内容与备份仍保留。',
  restoreHistoryFailed: '还原未完成，当前内容已保留。',
  openDocument: '打开文档', opening: '正在打开…', edit: '编辑', preview: '预览', saved: '已保存', pending: '待保存', saving: '保存中…',
  welcomeTitle: '打开一份文档', welcomeIntro: '阅读、编辑，让文字保持简单。', supportedFiles: '支持 .md 和 .markdown',
  notices: '文档通知与备份', documentMenu: '文档菜单', applicationMenu: '应用菜单', tabs: '文档标签', titlebar: '应用标题栏', documentBody: '文档正文',
  saveAs: '另存为…', immediateSave: '立即保存', history: '历史版本', backups: '本地备份…', backupsTitle: '本地备份',
  retry: '重试', cancel: '取消', cancelClose: '取消关闭', discardCloseMore: '丢弃并关闭…', discardClose: '丢弃并关闭',
  saveFailed: '修改尚未保存', conflict: '文件已被其他程序修改，自动保存已暂停。',
  missingDocument: '原文件已不存在，当前内容已保留。', unavailableDocument: '暂时无法读取原文件，当前内容已保留。',
  inspectDisk: '查看磁盘版本', useDisk: '使用磁盘版本', overwriteDisk: '覆盖磁盘版本', diskVersion: '磁盘版本', issues: '文档问题',
  recoveryPending: '恢复内容等待确认', recoveryBackedUp: '草稿已备份', recoveryWaiting: '草稿待备份', recoveryError: '草稿备份失败', processing: '正在处理文档',
  image: '图片', linkUnavailable: '此链接暂时无法打开', previewLoading: '正在生成预览…', previewFailed: '预览失败，请重新打开文档。', table: '表格，可横向滚动',
  closeLabel: (index: number) => `关闭第 ${index + 1} 个文档`, closeTitle: (name: string) => `关闭 ${name}`,
  tabError: '出错', readOnly: '只读',
  refreshBackups: '刷新备份', clearDrafts: '清理旧草稿', clearHistory: '清理历史', collapseBackups: '收起备份',
  backupDescription: '文档保存在你选择的位置。恢复草稿保留最近成功备份的修改；历史版本保留保存前的内容。',
  recoveryList: '恢复草稿', historyList: '当前文档历史', noRecovery: '没有待恢复草稿。', noHistory: '暂无历史版本。',
  timeUnavailable: '时间不可用', corruptBackup: '这份备份暂时无法读取，数据已保留', inspectDraft: '查看草稿', restoreDraft: '恢复草稿', discardDraft: '丢弃草稿',
  inspectHistory: '查看历史', exportHistory: '另存历史版本…', backupBody: '备份正文', bytes: '字节',
  cleanupDone: '清理完成。打开中文档的恢复草稿和无法读取的记录已保留。', exportDone: '历史版本已另存，当前文档保持不变。', backupActionFailed: '本地备份操作失败，当前文档已保留。',
  compositionPending: '输入尚未完成，请完成输入后重试。',
  openFailedRetained: '无法打开文件，当前文档已保留。',
  openFailed: '无法打开文件。',
  closeFailed: '暂时无法完成关闭，文档已保留。请稍后重试。',
  saveFailedRetained: '保存失败，当前修改已保留。',
  actionFailed: '操作失败，当前内容已保留。',
  fileUpdated: '文件已更新',
  closeConfirmationFailed: '暂时无法完成关闭，文档已保留。请稍后重试。',
  recoveryMaintenanceFailed: '文档已保存，但恢复草稿未能清理。备份已保留。',
  recoveryIncomplete: '最近的修改尚未备份，请保持文档打开。',
  recoveryFailedRetained: '未能备份最近的修改。请保持文档打开并重试。',
  editLimit: '内容过大，本次输入未应用。请缩短内容后重试。',
  recoverySpaceFull: '恢复空间已满',
  acknowledge: '知道了',
  continueWithoutHistory: '仅本次继续保存',
  closeBlocked: '文档尚未关闭',
  discardCloseDetail: '此操作会清理该文档关联的恢复草稿，不能撤销；不会回滚此前已经自动保存的内容。',
  fileMenu: '文件',
  closeDocument: '关闭当前文档',
  invalidRequest: '操作未能完成，请重试。',
  saveAsTitle: '另存为',
  replaceDetail: '选定文件的现有内容将被替换。',
  replace: '替换',
  directoryChange: '相对图片和链接将按新目录解析',
  directoryChangeDetail: '不会复制附件或改写相对链接。',
  continueSaveAs: '继续另存为',
  overwriteDetail: '本地内容将替换刚读取的磁盘版本；若磁盘再次变化，会停止写入。',
  overwrite: '覆盖',
  useDiskQuestion: '使用磁盘版本？',
  useDiskDetail: '当前本地修改将被丢弃。',
  exportHistoryTitle: '另存历史版本',
  exportHistoryDetail: '历史版本将另存到选定文件，当前标签保持不变。',
  staleSession: '文档状态已变化，请重试。',
  restoreIncomplete: '恢复未完成。',
  cleanupDetail: '不会删除原始文档。打开中文档的恢复草稿会保留；如需丢弃，请先关闭对应文档。',
  cleanup: '清理',
  cleanupQuestion: '清理本地备份记录？',
  discardDraftQuestion: '丢弃此恢复草稿？',
  openingWait: '正在打开文件，请稍候。',
  processingWait: '正在处理文档，请稍候。',
  closingWait: '正在确认关闭，请稍候。',
  recoveryAlreadyOpen: '恢复内容已在标签中打开；请先处理并关闭该标签。',
  markdownName: '请使用 .md 或 .markdown 文件名。',
  historyTargetOpen: '请选择尚未打开的其他文件来保存历史版本。',
  unsafeTarget: '无法覆盖目标文件，请选择其他位置。',
  targetDirectoryChanged: '目标目录已变化，请重新选择。',
  exportTargetChanged: '目标文件已变化，请重新确认。',
  exportChangedAfterWrite: '另存后目标文件发生变化，请检查目标文件。',
  invalidClose: '暂时无法完成关闭，文档已保留。请稍后重试。',
  closeTimeout: '暂时无法完成关闭，文档已保留。请稍后重试。',
  closeExternalChange: '原文件已在外部更改或不可用，请先处理该文档。',
  closeRecoveryPending: '恢复内容等待确认，请先处理该文档。',
  discardUnconfirmed: '无法确认恢复草稿已丢弃，文档已保留。',
  saveMissing: '原文件已不存在，未创建或覆盖文件。当前修改已保留。',
  saveDiskFull: '磁盘空间不足，修改尚未保存。',
  saveDenied: '没有写入权限，修改尚未保存。',
  saveBusy: '文件被占用，请稍后重试。',
  saveUnconfirmed: '保存未能确认完成，当前修改已保留。请检查磁盘文件后重试。',
  invalidSave: '无法保存，请重试。当前修改已保留。',
  readOnlyDocument: '当前文档仅供只读查看。',
  readOnlyCopy: '只能另存当前只读文件的原始内容。',
  duplicateSave: '保存内容已变化，请重试。',
  invalidSaveText: '内容格式不受支持或文件过大，修改尚未保存。',
  staleSave: '内容已变化，请重新保存。',
  saveBaselineChanged: '文件已变化，自动保存已暂停。当前修改已保留。',
  saveCancelledChanged: '文档已变化，本次保存已取消。',
  historySourceChanged: '备份旧版本时文件发生变化，请重试。',
  targetOpen: '目标文件已在另一文档中打开，请先处理该文档。',
  readOnlyOriginal: '只读原文件及其别名不能写回，请选择新的普通文件。',
  unsafeWritableTarget: '目标文件不能安全覆盖，请选择普通可写文件。',
  chooseChangedDirectory: '目标目录已变化，请重新选择。',
  targetAlreadyOpen: '目标文件已在另一文档中打开。',
  targetChanged: '目标文件已在外部更改，请重新确认。',
  changedAfterSave: '写入后发现外部变化，当前修改已保留。',
  sourceChangedOrReadOnly: '原文件已在外部更改或不再可写，已停止写入并保留当前修改。',
  resolveConflictFirst: '原文件已在外部更改，请先处理冲突。',
  changedDuringClose: '关闭期间内容发生变化，已保留文档。',
  changedDuringWindowClose: '关闭期间内容发生变化，已保留最新草稿和全部文档。',
  fileMissing: '文件不存在，请重新选择。',
  readDenied: '没有读取文件的权限。',
  readFailed: '无法读取文件，当前文档已保留。',
  fileTooLarge: '文件过大，无法打开。',
  changedDuringRead: '文件在读取时发生变化，请重试。',
  unsupportedFile: '请选择 .md 或 .markdown 文件。',
  regularMarkdownOnly: '只能打开普通 Markdown 文件。',
  loadLimit: '文件过大，无法打开。请使用其他工具查看。',
  loadLimitShort: '文件过大，无法打开。',
  corruptRecoveryIndex: '无法读取恢复草稿，原数据已保留。',
  invalidRecoveryOrder: '恢复草稿不完整，原数据已保留。',
  corruptDiscardMarker: '无法确认草稿的丢弃状态，原数据已保留。',
  untitled: '未命名文档',
  unreadableRecovery: '无法读取的恢复记录',
  invalidRecoveryId: '无法找到这份恢复草稿。',
  alreadyDiscarded: '此恢复记录已经丢弃。',
  noRecoveryContent: '没有待恢复内容。',
  invalidRecoveryContent: '恢复草稿格式不受支持，原数据已保留。',
  staleRecoverySession: '文档已变化，请重新备份。',
  staleRecoverySnapshot: '内容已变化，请重新备份。',
  discardedRecoverySession: '这份草稿已丢弃，无法再次备份。',
  staleRecoveryRevision: '内容已变化，请重新备份。',
  inconsistentRecovery: '备份内容不一致，原数据已保留。',
  noRecoveryNeeded: '当前内容已保存，无需备份草稿。',
  recoveryCapacity: '恢复空间已满。打开中文档的备份已保留，请清理旧草稿后重试。',
  cleanupCancelled: '已取消清理，当前内容尚未备份。',
  recoveryWriteFailed: '未能备份最近的修改。请保持文档打开并重试。',
  changedAfterDiscard: '确认丢弃后内容发生变化，已保留最新草稿和文档。',
  activeRecovery: '请先关闭对应文档，再清理这份恢复草稿。',
  invalidReadOnlyState: '只读文档已变化，请重新打开。',
  invalidCurrentState: '文档状态已变化，当前内容已保留。请重试。',
  defaultFilename: '文档.md',
  diskChangedAgain: '磁盘版本再次变化，请重新查看并确认。',
  corruptHistoryIndex: '无法读取历史版本，原数据已保留。',
  duplicateHistory: '历史记录不完整，原数据已保留。',
  historyCapacity: '备份空间不足，未能备份旧版本。自动保存已暂停。',
  historyWriteFailed: '未能备份旧版本，自动保存已暂停。',
  historyMismatch: '此历史版本不属于当前文档。',
  targetOtherWindow: '目标文件已在其他窗口打开。',
  recoveryDuringSave: '文件正在保存，请稍后恢复草稿。',
  recoveryTabLimit: '已打开20个文档，请先关闭一个再恢复。',
  originalAlreadyOpen: '原文件已打开；请先处理并关闭该标签，再恢复草稿。',
  invalidWindow: '窗口状态已变化，请重试。',
  tabLimit: '已打开20个文档，请先关闭一个再打开。',
  backupDirectoryLink: '无法访问备份目录，请检查目录权限和位置。',
  invalidBackupId: '无法找到这份备份。',
  invalidBackupDirectory: '无法访问备份目录。',
  invalidBackupFilename: '无法读取这份备份，原数据已保留。',
  invalidBackupFile: '无法读取这份备份，原数据已保留。',
  backupChanged: '备份内容发生变化，请重试。',
  corruptBackupIndex: '无法读取备份记录，原数据已保留。',
  backupIntegrityFailed: '备份内容不完整，原数据已保留。',
  backupIncomplete: '备份内容不完整，已保留原数据。',
  backupIndexLink: '无法安全访问备份记录，请检查备份目录。',
  evictRecoveryDetail: (count: number) => `需要清理 ${count} 份最旧的恢复草稿。打开中文档的备份会保留。`,
  evictedRecovery: (count: number) => `已清理 ${count} 份旧草稿`, evictedRecoveryDetail: '原始文档未删除，打开中文档的恢复草稿已保留。',
  historyUnavailable: (name: string) => `无法保留「${name}」的旧版本`, skipHistoryDetail: '仅本次跳过历史并继续保存，会失去本次覆盖前的历史版本。',
  closeFailureTitle: (name: string) => `「${name}」尚未关闭`, closeFailureDetail: (name: string) => `未能保存「${name}」。关闭前请重试或另存为。`,
  discardCloseQuestion: (name: string) => `丢弃「${name}」尚未保存的内容并关闭？`,
  replaceQuestion: (name: string) => `替换「${name}」？`, overwriteQuestion: (name: string) => `覆盖「${name}」的磁盘版本？`,
  diskModifiedDetail: (detail: string, modifiedAt: string) => `${detail}\n磁盘更新时间：${modifiedAt}`, historyFilename: (name: string, savedAt: string) => {
    const date = new Date(savedAt); const pad = (n: number) => String(n).padStart(2, '0')
    return `${name.replace(/\.(?:md|markdown)$/iu, '')}-历史-${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}-${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}.md`
  },
  restoreDocuments: '恢复未保存稿', source: 'Markdown 源码', about: '关于 InkNest', hide: '隐藏 InkNest', hideOthers: '隐藏其他应用', showAll: '显示全部', quit: '退出 InkNest', undo: '撤销', redo: '重做', cut: '剪切', copyText: '复制', paste: '粘贴', selectAll: '全选', editor: '文档编辑区',
} as const

export const resourceCopy: Record<ResourceBlockedReason, string> = {
  unsaved: '保存文档后可加载相对路径图片',
  path: '此图片路径不能直接加载，请将图片放在文档目录内并使用相对路径，或点击打开图片', syntax: '图片地址包含标题，请将标题移到 > 之后，例如：![说明](<images/photo.png> "标题")', missing: '图片不存在', access: '无法访问这张图片', format: '暂不支持此图片格式', size: '图片过大，无法显示', remote: '远程图片未加载', unavailable: '图片暂时无法显示'
}
export const readOnlyCopy: Record<ReadOnlyReason, string> = {
  encoding: '只读 · 此文件的编码暂不支持编辑', 'mixed-eol': '只读 · 此文件的换行格式暂不支持编辑', size: '只读 · 文件过大',
  link: '只读 · 链接文件暂不支持编辑', filesystem: '只读 · 当前文件系统暂不支持编辑', permission: '只读 · 当前文件没有写入权限'
}
export const errorCopy: Record<ErrorCode, string> = {
  NOT_FOUND: '文件不存在，请重新选择。', ACCESS_DENIED: '没有写入权限，修改尚未保存。', UNSUPPORTED_TYPE: '请选择 .md 或 .markdown 文件。', TOO_LARGE: '文件过大，无法打开。',
  INVALID_REQUEST: '操作未能完成，请重试。', STALE_SESSION: '文档状态已变化，请重试。', IO_ERROR: '操作失败，当前内容已保留。', FILE_BUSY: '文件被占用，请稍后重试。',
  STALE_REVISION: '内容已变化，请重试。', EXTERNAL_CHANGE: copy.conflict, DISK_FULL: '磁盘空间不足，修改尚未保存。', READ_ONLY: '当前文档仅供只读查看。',
  TAB_LIMIT: '已打开20个文档，请先关闭一个再打开。', TARGET_OPEN: '目标文件已在另一文档中打开，请先处理该文档。',
  RECOVERY_FAILED: '未能备份最近的修改。请保持文档打开并重试。', HISTORY_FAILED: '未能备份旧版本，自动保存已暂停。', CORRUPT_DATA: '备份无法读取，原数据已保留。'
}
